os: osx
language: rust
rust:
  # stable is unsupport 2018 edition
  # - stable
  - beta
  - nightly
before_script:
  - rustup component add clippy-preview
  - rustup component add rustfmt-preview
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test
  - cargo fmt
before_deploy:
  - cargo build --release
  - mkdir "rmemo-${TRAVIS_TAG}"
  - cp target/release/rmemo LICENSE README.md "rmemo-${TRAVIS_TAG}"
  - zip "rmemo-${TRAVIS_TAG}.zip" -r "rmemo-${TRAVIS_TAG}"
# deploy:
#   provider: releases
#   api_key: $GITHUB_TOKEN
#   file: rmemo-${TRAVIS_TAG}.zip
#   skip_cleanup: true
#   on:
#     tags: true
