[package]
name = "rmemo"
version = "0.1.8"
authors = ["k-nasa <htilcs1115@gmail.com>"]
keywords = ["cli"]
repository = "https://github.com/k-nasa/memo_command"
license-file = "LICENSE"
readme = "README.md"
description = "Tools for taking notes fast on the CLI"

[dependencies]
dirs = "1.0.4"
toml = "0.4.8"
chrono = "0.4"
serde = "1.0"
serde_derive = "1.0"
clap = "2.32"
colored = "1.6"
termion = "1.5"
