[package]
name = "memo"
version = "0.1.0"
authors = ["k-nasa <htilcs1115@gmail.com>"]
description = "CLI memo command"

[dependencies]
dirs = "1.0.4"
toml = "0.4.6"
chrono = "0.4"
serde = "*"
serde_derive = "*"
clap = "*"
colored = "1.6"
